mutation CreateUser(
  $id: String!,
  $username: String!,
  $email: String!,
  $displayName: String
) @auth(level: USER) {
  user_insert(data: {
    id: $id
    username: $username
    email: $email
    displayName: $displayName
  })
}

mutation UpdateUserProfile(
  $id: String!,
  $username: String!,
  $email: String!,
  $displayName: String,
  $bio: String,
  $location: String,
  $profilePictureUrl: String
) @auth(level: USER) {
  user_upsert(data: {
    id: $id
    username: $username
    email: $email
    displayName: $displayName
    bio: $bio
    location: $location
    profilePictureUrl: $profilePictureUrl
  })
}

mutation CreatePost(
  $userId: String!,
  $content: String!,
  $imageUrl: String!,
  $locationTag: String,
  $zipCode: String,
  $top: String,
  $bottom: String,
  $outerwear: String,
  $wornAt: Timestamp
) @auth(level: USER) {
  post_insert(data: {
    user: { id: $userId }
    content: $content
    imageUrl: $imageUrl
    locationTag: $locationTag
    zipCode: $zipCode
    top: $top
    bottom: $bottom
    outerwear: $outerwear
    wornAt: $wornAt
  })
}

mutation SendFriendRequest(
  $fromUserId: String!,
  $toUserId: String!
  $createdAt: Timestamp!
) @auth(level: USER) {
  friendRequest_insert(data: {
    fromUser: { id: $fromUserId }
    toUser: { id: $toUserId }
    status: "pending"
    createdAt: $createdAt
  })
}

mutation AcceptFriendRequest(
  $id: UUID!
) @auth(level: USER) {
  friendRequest_update(id: $id, data: {
    status: "accepted"
  })
}

mutation DeclineFriendRequest(
  $id: UUID!
) @auth(level: USER) {
  friendRequest_delete(id: $id)
}

mutation CreateLike($postId: UUID!, $userId: String!, $createdAt: Timestamp!)
@auth(level: USER) {
  like_insert(data: {
    postId: $postId
    userId: $userId
    createdAt: $createdAt
  })
}

mutation CreateComment($postId: UUID!, $userId: String!, $content: String!, $createdAt: Timestamp!)
@auth(level: USER) {
  comment_insert(data: {
    postId: $postId
    userId: $userId
    content: $content
    createdAt: $createdAt
  })
}