# dataconnect/example/mutations.gql

mutation CreateUser($id: String!, $username: String!, $email: String!, $displayName: String) 
  @auth(level: USER) { # Allows any logged-in user to call this
  user_insert(data: {
    id: $id,
    username: $username,
    email: $email,
    displayName: $displayName
  })
}