query listPosts @auth(level: PUBLIC) {
  posts {
    id
    content
    imageUrl
    locationTag
    zipCode
    top
    bottom
    outerwear
    wornAt
    createdAt
    user {
      id
      username
      displayName
      profilePictureUrl
    }
  }
}

query getOutfits($userId: String!) @auth(level: USER) {
  outfitRecommendations(where: { user: { id: { eq: $userId } } }) {
    imageUrl
    description
  }
}

query listAllUsers @auth(level: USER) {
  users {
    id
    username
    displayName
    profilePictureUrl
    location
  }
}

query getLikesForPost($postId: UUID!) @auth(level: PUBLIC) {
  likes(where: { postId: { eq: $postId } }) {
    _id
    postId
    createdAt
    user {
      id
      username
      displayName
    }
  }
}

query getCommentsForPost($postId: UUID!) @auth(level: PUBLIC) {
  comments(where: { postId: { eq: $postId } }) {
    id
    postId
    content
    createdAt
    user {
      id
      username
      displayName
    }
  }
}

query GetUserProfile($id: String!) @auth(level: USER) {
  user(id: $id) {
    id
    username
    displayName
    bio
    location
    profilePictureUrl
    createdAt
  }
}

query GetIncomingRequests($userId: String!) @auth(level: USER) {
  friendRequests(
    where: {
      toUser: { id: { eq: $userId } }
      status: { eq: "pending" }
    }
  ) {
    id
    fromUser {
      id
      username
      displayName
    }
  }
}

query GetFriends($userId: String!) @auth(level: USER) {
  friendRequests(
    where: {
      status: { eq: "accepted" }
    }
  ) {
    id
    fromUser {
      id
      username
      displayName
    }
    toUser {
      id
      username
      displayName
    }
  }
}