# dataconnect/example/queries.gql

query listPosts @auth(level: PUBLIC) { 
  posts {
    id
    content
    user {
      username
    }
  }
}

query getOutfits($userId: String!) @auth(level: USER) {
  outfitRecommendations(where: { user: { id: { eq: $userId } } }) {
    imageUrl
    description
  }
}
query listAllUsers @auth(level: PUBLIC) {
  users {
    id
    username
    email
    displayName
    createdAt
  }
}