extend type Query {
  """
  ✨ Look up a single `Comment` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  comment(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Comment_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Comment_FirstRow
  ): Comment @fdc_generated(from: "Comment", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Like` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  like(
    """
    The key used to identify the object.
    """
    key: Like_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Like_FirstRow
  ): Like @fdc_generated(from: "Like", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `OutfitRecommendation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  outfitRecommendation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: OutfitRecommendation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: OutfitRecommendation_FirstRow
  ): OutfitRecommendation @fdc_generated(from: "OutfitRecommendation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `Post` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  post(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Post_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Post_FirstRow
  ): Post @fdc_generated(from: "Post", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `SavedOutfit` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  savedOutfit(
    """
    The key used to identify the object.
    """
    key: SavedOutfit_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: SavedOutfit_FirstRow
  ): SavedOutfit @fdc_generated(from: "SavedOutfit", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: String

    """
    ✨ `_expr` server value variant of `id` (The unique ID of the object.)
    """
    id_expr: String_Expr

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Comment` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  comments(
    """
    Filter condition to narrow down the query results.
    """
    where: Comment_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Comment_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Comment_Having
  ): [Comment!]! @fdc_generated(from: "Comment", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Like` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  likes(
    """
    Filter condition to narrow down the query results.
    """
    where: Like_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Like_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Like_Having
  ): [Like!]! @fdc_generated(from: "Like", purpose: QUERY_MULTIPLE)
  """
  ✨ List `OutfitRecommendation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  outfitRecommendations(
    """
    Filter condition to narrow down the query results.
    """
    where: OutfitRecommendation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [OutfitRecommendation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: OutfitRecommendation_Having
  ): [OutfitRecommendation!]! @fdc_generated(from: "OutfitRecommendation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `Post` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  posts(
    """
    Filter condition to narrow down the query results.
    """
    where: Post_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Post_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Post_Having
  ): [Post!]! @fdc_generated(from: "Post", purpose: QUERY_MULTIPLE)
  """
  ✨ List `SavedOutfit` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  savedOutfits(
    """
    Filter condition to narrow down the query results.
    """
    where: SavedOutfit_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [SavedOutfit_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: SavedOutfit_Having
  ): [SavedOutfit!]! @fdc_generated(from: "SavedOutfit", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
