type User @table {
  id: String! @default(expr: "auth.uid")
  username: String!
  email: String!
  displayName: String
  createdAt: Timestamp! @default(expr: "request.time")
  bio: String
  profilePictureUrl: String
  location: String
}

type Post @table {
  user: User!
  content: String!
  createdAt: Timestamp! @default(expr: "request.time")
  imageUrl: String!
  locationTag: String
  zipCode: String
  tops: [String!]
  topMaterials: [String!]
  bottoms: [String!]
  bottomMaterials: [String!]
  outerwear: [String!]
  outerwearMaterials: [String!]
  wornAt: Timestamp
  isPublic: Boolean! @default(expr: "true")
}

type Comment @table {
  user: User!
  post: Post!
  content: String!
  createdAt: Timestamp! @default(expr: "request.time")
}

type Like @table(key: ["user", "post"]) {
  user: User!
  post: Post!
  createdAt: Timestamp! @default(expr: "request.time")
}

type OutfitRecommendation @table {
  user: User!
  weatherCondition: String!
  temperatureRange: String!
  imageUrl: String!
  createdAt: Timestamp! @default(expr: "request.time")
  description: String
  clothingItems: [String!]
}

type SavedOutfit @table(key: ["user", "outfitRecommendation"]) {
  user: User!
  outfitRecommendation: OutfitRecommendation!
  createdAt: Timestamp! @default(expr: "request.time")
  notes: String
}

type OutfitFeedback @table {
  user: User!
  post: Post!
  rating: String!
  temperature: Float
  weatherCondition: String
  createdAt: Timestamp! @default(expr: "request.time")
}